# Site settings
title: ubaldo.pescato.re
email: ubaldo@pescato.re
description: > # this means to ignore newlines until "baseurl:"
  A left-handed italian human being.
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
# twitter_username: twitter_username
github_username:  P3trur0

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  poetry:
    output: true
    permalink: /poetry/:path/


